In [1]:
import numpy as np

![](./support-files/Week2_Vectorization_table.jpg)

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0,0.9 ]])

In [3]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
#Sum lines of each column
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = A/cal.reshape(1,4)
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


In [6]:
percentage = A/cal
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


Broadcast in np documentation:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast.html